import { Inter } from 'next/font/google';
import './global.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'] })



export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body >
        <div className={inter.className}>
          {children}
        </div>
      </body>
    </html>
  );
}